version: '3.7'

services:
  baseapi.api:
    image: ${DOCKER_REGISTRY-}baseapiapi
    container_name: BaseApi.Api
    build:
      context: .
      dockerfile: BaseApi.Api/Dockerfile
    environment:     
      DB_PASSWORD: "Strong_password_123!"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      - baseapi.database

  baseapi.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: BaseApi.Db
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strong_password_123!"
    ports:
      - "1433:1433"

  baseapi.seq:
    image: datalust/seq:latest
    container_name: BaseApi.Seq
    environment:
      ACCEPT_EULA: 'Y'
    ports:
      - 5341:5341
      - 8081:80

  baseapi.cache:
    image: redis:latest
    container_name: BaseApi.Cache
    restart: always
    ports:
      - 6379:6379

  baseapi.queue:
    image: rabbitmq:management
    container_name: BaseApi.Queue
    hostname: baseapi-mq
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest

  baseapi.storage:
    image: localstack/localstack
    container_name: BaseApi.Storage
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"